### ISSUE TITLE
Errors in running the demo

### ISSUE THREAD

**Issue by zebehn** [mimesis-inria/DeepPhysX#3]
I installed the packages by following the instructions and got an error as follows.
Can you help resolving the error?

```
Core % python3 demo.py armadillo
Connecting to DeepPhysX online storage to download missing data...
	Downloading file 1/7 in Environment/models/armadillo.obj
	Downloading file 2/7 in Environment/models/armadillo_coarse.obj
	Downloading file 3/7 in Environment/models/sparse_grid.obj
	Downloading file 4/7 in sessions/armadillo_dpx/infos.txt
	Downloading file 5/7 in sessions/armadillo_dpx/dataset/dataset.json
	Downloading file 6/7 in sessions/armadillo_dpx/network/network.pth
	Downloading file 7/7 in sessions/armadillo_dpx/stats/events.out.tfevents.1651475113.romulus
Directory conflict: you are going to overwrite sessions/armadillo_dpx.
Create a new directory /Users/zebehn/Development/DeepPhysX/Core/examples/demos/Armadillo/FC/sessions/armadillo_dpx_1/ for this session.
Traceback (most recent call last):
  File "/Users/zebehn/Development/DeepPhysX/Core/examples/demos/Armadillo/FC/interactive.py", line 56, in <module>
    launch_runner()
  File "/Users/zebehn/Development/DeepPhysX/Core/examples/demos/Armadillo/FC/interactive.py", line 44, in launch_runner
    runner = BaseRunner(session_dir='sessions',
  File "/Users/zebehn/opt/anaconda3/envs/deep/lib/python3.10/site-packages/DeepPhysX/Core/Pipelines/BaseRunner.py", line 58, in __init__
    self.manager = Manager(pipeline=self,
  File "/Users/zebehn/opt/anaconda3/envs/deep/lib/python3.10/site-packages/DeepPhysX/Core/Manager/Manager.py", line 64, in __init__
    self.network_manager = NetworkManager(manager=self,
  File "/Users/zebehn/opt/anaconda3/envs/deep/lib/python3.10/site-packages/DeepPhysX/Core/Manager/NetworkManager.py", line 56, in __init__
    raise ValueError(f"[{self.name}] Training requires a loss and an optimizer in your NetworkConfig")
ValueError: [NetworkManager] Training requires a loss and an optimizer in your NetworkConfig
(deep) zebehn@jangminsuui-MacBookPro Core % python3 demo.py armadillo
Directory conflict: you are going to overwrite sessions/armadillo_dpx.
Create a new directory /Users/zebehn/Development/DeepPhysX/Core/examples/demos/Armadillo/FC/sessions/armadillo_dpx_2/ for this session.
Traceback (most recent call last):
  File "/Users/zebehn/Development/DeepPhysX/Core/examples/demos/Armadillo/FC/interactive.py", line 56, in <module>
    launch_runner()
  File "/Users/zebehn/Development/DeepPhysX/Core/examples/demos/Armadillo/FC/interactive.py", line 44, in launch_runner
    runner = BaseRunner(session_dir='sessions',
  File "/Users/zebehn/opt/anaconda3/envs/deep/lib/python3.10/site-packages/DeepPhysX/Core/Pipelines/BaseRunner.py", line 58, in __init__
    self.manager = Manager(pipeline=self,
  File "/Users/zebehn/opt/anaconda3/envs/deep/lib/python3.10/site-packages/DeepPhysX/Core/Manager/Manager.py", line 64, in __init__
    self.network_manager = NetworkManager(manager=self,
  File "/Users/zebehn/opt/anaconda3/envs/deep/lib/python3.10/site-packages/DeepPhysX/Core/Manager/NetworkManager.py", line 56, in __init__
    raise ValueError(f"[{self.name}] Training requires a loss and an optimizer in your NetworkConfig")
ValueError: [NetworkManager] Training requires a loss and an optimizer in your NetworkConfig
```

**Comment by RobinEnjalbert** [comment]
Hi @zebehn ,
I close this issue for now as you did not reported any other problem.
See you !
